### ISSUE TITLE
Adding WMTS service reads available layer names but returns error when adding layer

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2327]
When adding this WMTS service:

https://gibs-a.earthdata.nasa.gov/wmts/epsg4326/best/wmts.cgi

TerriaJS successfully reads the layer names from the service, but when actually trying to add one of the layers to the map this error is shown:

```
An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property 'east' of undefined
TypeError: Cannot read property 'east' of undefined
    at Function.l.intersection (http://nationalmap.gov.au/build/nationalmap.js:15:28569)
    at V._createTileImagerySkeletons (http://nationalmap.gov.au/build/nationalmap.js:107:6444)
    at http://nationalmap.gov.au/build/nationalmap.js:500:10777
    at y.forEachLoadedTile (http://nationalmap.gov.au/build/nationalmap.js:504:6636)
    at W._onLayerAdded (http://nationalmap.gov.au/build/nationalmap.js:500:10745)
    at W._onLayerShownOrHidden (http://nationalmap.gov.au/build/nationalmap.js:500:11293)
    at i.raiseEvent (http://nationalmap.gov.au/build/nationalmap.js:15:4170)
    at c._update (http://nationalmap.gov.au/build/nationalmap.js:500:17028)
    at W.initialize (http://nationalmap.gov.au/build/nationalmap.js:500:7650)
    at y.beginFrame (http://nationalmap.gov.au/build/nationalmap.js:504:7160)
```

We are intending to add some of the layers from this service to GEOGLAM.

**Comment by tephenavies** [comment]
The associated catalog item has a `rectangle` that is just a point, so intersecting the `CatalogItem`'s rectangle with the `ImageryProvider`'s rectangle results in an `undefined` rectangle. Further intersecting this with a tile's rectangle throws the error.

The `CatalogItem` most likely gets its rectangle from the server, so the server is sending wrong bounds. (@kring is that correct?)

**Comment by kring** [comment]
Looks like the server is specifying "whole world" for the bounding box:
![image](https://cloud.githubusercontent.com/assets/924374/21919629/d2b9e9b8-d9af-11e6-843b-f7bb49adab51.png)

(from https://gibs-a.earthdata.nasa.gov/wmts/epsg4326/best/wmts.cgi?service=WMTS&request=GetCapabilities)

So I'm not sure where we're getting that degenerate rectangle from.  Maybe we're interpreting it wrong?

**Comment by steve9164** [comment]
I found a problem: the WMTS rectangle was being created using only the lower left point of the bounding box, but the service still doesn't work

**Comment by tephenavies** [comment]
Overall problem is that the`SupportedCRS` of the `TileMatrixSet`s is `"urn:ogc:def:crs:OGC:1.3:CRS84"` (EPSG4326), not Web Mercator.

**Comment by tephenavies** [comment]
This one works though (with the fix I'm about to PR): https://gibs-a.earthdata.nasa.gov/wmts/epsg3857/best/wmts.cgi

**Comment by meh9** [comment]
Nice!
