### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by zdefne-usgs** [TerriaJS/terriajs#3140]
I am trying to install a second instance of Terrimap with Docker but I get a "502 Bad Gateway" error when I test it on my browser. 
docker logs show 
```
Error: Cannot find module '/usr/local/app/TerriaMap/node_modules/terriajs-server/lib/app.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```
I do not get any error messages while building the docker image. Both TerriMap and Terriajs packages point to "terriajs-server": "^2.7.4".  What could be the issue?  
Thanks

**Comment by zdefne-usgs** [comment]
This issue was a bad syntax in the Dockerfile while cloning the repository. The directory already existed, but no error message was created while building the image. So the container did not have any of the required folders in it, hence complained about the entry point.
