### ISSUE TITLE
v7.9 ArcGIS server cesium worker fail

### ISSUE THREAD

**Issue by hardreddata** [TerriaJS/terriajs#3824]
http://ci.terria.io/master/ using a 3D map

(and also on our local v7.9 TerriaMap - I don't know of a public one which has been updated)

1. Add the Surface Geology layer
2. Click on it to bring up feature info
3. Scroll with mouse

Observe error

```
TypeError: Transforms.require is not a function
TypeError: Transforms.require is not a function
    at Object../node_modules/terriajs-cesium/Source/Workers/createGroundPolylineGeometry.js.ApproximateTerrainHeights.initialize (http://ci.terria.io/master/build/cesiumWorkers.js:51310:34)
    at createGroundPolylineGeometry (http://ci.terria.io/master/build/cesiumWorkers.js:52577:46)
    at createGeometry (http://ci.terria.io/master/build/cesiumWorkers.js:51036:44)
    at callAndWrap (http://ci.terria.io/master/build/cesiumWorkers.js:58003:35)
    at http://ci.terria.io/master/build/cesiumWorkers.js:58048:34
OK
```

Chrome Version 78.0.3904.108 (Official Build) (64-bit) and Firefox 70.0.1 (64-bit) on Windows both impacted. IE11 is not impacted. 

I think associated with ArcGIS polygon or image layers (geology, aerials).

I get that the CesiumJS workers have just been rewritten.

Many thanks!

**Comment by kring** [comment]
Thanks @RussellGrew. I've published terriajs-cesium 1.63.3 which fixes this. So it's working on http://ci.terria.io/master/ now, and it'll also be fixed in the next terriajs release published to npm.
