### ISSUE TITLE
Renderer crash when viewing at 90º

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#559]
I was mucking around a little bit, and moved the viewpoint so I was looking flat across the landscape (horizon in the centre of the screen).

```
RangeError: Invalid array length
RangeError: Invalid array length
    at o (http://nationalmap.nicta.com/build/ausglobe.js:65:23481)
    at s (http://nationalmap.nicta.com/build/ausglobe.js:65:25376)
    at _ (http://nationalmap.nicta.com/build/ausglobe.js:65:30245)
    at yt.render (http://nationalmap.nicta.com/build/ausglobe.js:66:4091)
    at M.render (http://nationalmap.nicta.com/build/ausglobe.js:127:3551)
    at t (http://nationalmap.nicta.com/build/ausglobe.js:126:22344)
```

I can't reproduce it.

**Comment by kgrochow** [comment]
I can't reproduce it either.
