### ISSUE TITLE
Height must be a power of two to call generateMipmap()

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#640]
1. Add data: https://mapsengine.google.com/09372590152434720789-00913315481290556980-4/wms/
2. Enable layer: Action_Park_1985_site_vector_LGATE_22102014
3. Click to zoom to layer

```
DeveloperError: height must be a power of two to call generateMipmap().
Error
    at new i (http://vagrant-nationalmap:3001/build/ausglobe.js:33:22017)
    at f.generateMipmap (http://vagrant-nationalmap:3001/build/ausglobe.js:56:380)
    at i (http://vagrant-nationalmap:3001/build/ausglobe.js:61:29443)
    at q.k._reprojectTexture (http://vagrant-nationalmap:3001/build/ausglobe.js:62:3918)
    at o.processStateMachine (http://vagrant-nationalmap:3001/build/ausglobe.js:61:27890)
    at n.processStateMachine (http://vagrant-nationalmap:3001/build/ausglobe.js:70:6025)
    at Function.D.processStateMachine (http://vagrant-nationalmap:3001/build/ausglobe.js:61:11204)
    at Q.F.loadTile (http://vagrant-nationalmap:3001/build/ausglobe.js:61:22705)
    at l (http://vagrant-nationalmap:3001/build/ausglobe.js:67:12606)
    at S.update (http://vagrant-nationalmap:3001/build/ausglobe.js:67:14670)
```

**Comment by kring** [comment]
The problem here is that we're requesting an image that is 256x256, and the server is returning one that is 256x257.  Thanks GME.  Here's the problematic URL:

https://mapsengine.google.com/09372590152434720789-00913315481290556980-4/wms/?transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=09372590152434720789-14989446372575920390-4&srs=EPSG%3A3857&bbox=12523442.714243278%2C-5009377.085697312%2C15028131.257091936%2C-2504688.542848654&width=256&height=256

**Comment by stevage** [comment]
Any workarounds? GME goes away at the start of next year, but it'd be nice
if these layers worked till then. Does swallowing the exception work, or
would then nothing get drawn?

**Comment by kring** [comment]
Yeah it should be possible to just skip the `generateMipmaps` call for NPOT textures.  That can have a visual quality impact, but only for these buggy tiles, and it's better than crashing.
