### ISSUE TITLE
Bug: Callstack exceeded in CalculateDomain when switching region aggregation 

### ISSUE THREAD

**Issue by ljowen** [TerriaJS/terriajs#6941]
**Steps to reproduce**

1. Visit https://nationalmap.gov.au/#share=s-tkQhVRPh5p88SD55gbMYGdGq2IJ
2. Change _Building approvals by SA2 and above > Region type 3 times_
3. App crashes with following error:

```
3.TerriaMap.js:163 RangeError: Maximum call stack size exceeded
    at t.calculateDomain (3.TerriaMap.js:77:495048)
    at 3.TerriaMap.js:68:49236
    at Array.map (<anonymous>)
    at y.get (3.TerriaMap.js:68:48648)
    at et (3.TerriaMap.js:1:27840)
    at t.computeValue_ (3.TerriaMap.js:1:26050)
    at t.trackAndCompute (3.TerriaMap.js:1:25894)
    at t.get (3.TerriaMap.js:1:25130)
    at t.getObservablePropValue_ (3.TerriaMap.js:1:57896)
    at y.get (3.TerriaMap.js:1:62674)
```

**Comment by nf-s** [comment]
Good find!

I think this is why

<img width="700" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/117eed12-a420-48be-8759-a718e41b25d1">

Massive spread operator.

Interestingly, Firefox doesn't complain (on Mac) - but Chrome will crash
