### ISSUE TITLE
Netlify fails with ReferenceError: TransformStream not defined

### ISSUE THREAD

**Issue by pjonsson** [TerriaJS/terriajs#7106]
I made a PR which fixed some unused import warnings, and that failed in Netlify with:
``` 
0:27:12 AM: [08:27:12] Finished "copyToBuild" after 16 ms
10:27:12 AM: [08:27:12] Starting "generateMemberPages"...
10:27:13 AM: Failed during stage "building site": Build script returned non-zero exit code: 2
10:27:13 AM: webpack:///./node_modules/@zip.js/zip.js/lib/core/streams/crc32-stream.js?:36
10:27:13 AM: class Crc32Stream extends TransformStream {
10:27:13 AM:                           ^
10:27:13 AM: ReferenceError: TransformStream is not defined
10:27:13 AM:     at eval (webpack:///./node_modules/@zip.js/zip.js/lib/core/streams/crc32-stream.js?:36:27)
10:27:13 AM:     at Module../node_modules/@zip.js/zip.js/lib/core/streams/crc32-stream.js (/opt/build/repo/build/generateDocs.js:6658:1)
10:27:13 AM:     at __webpack_require__ (/opt/build/repo/build/generateDocs.js:26:30)
10:27:13 AM:     at eval (webpack:///./node_modules/@zip.js/zip.js/lib/core/streams/zip-entry-stream.js?:4:74)
10:27:13 AM:     at Module../node_modules/@zip.js/zip.js/lib/core/streams/zip-entry-stream.js (/opt/build/repo/build/generateDocs.js:6694:1)
10:27:13 AM:     at __webpack_require__ (/opt/build/repo/build/generateDocs.js:26:30)
10:27:13 AM:     at eval (webpack:///./node_modules/@zip.js/zip.js/lib/core/streams/codec-stream.js?:12:78)
10:27:13 AM:     at Module../node_modules/@zip.js/zip.js/lib/core/streams/codec-stream.js (/opt/build/repo/build/generateDocs.js:6586:1)
10:27:13 AM:     at __webpack_require__ (/opt/build/repo/build/generateDocs.js:26:30)
10:27:13 AM:     at eval (webpack:///./node_modules/@zip.js/zip.js/lib/core/codec-pool.js?:5:82)
10:27:13 AM: [08:27:13] "generateMemberPages" errored after 725 ms
10:27:13 AM: [08:27:13] Error in plugin "user-doc"
10:27:13 AM: Message:
10:27:13 AM:     Generating catalog members pages exited with an error.
10:27:13 AM: Details:
10:27:13 AM:     domainThrown: true
10:27:13 AM: [08:27:13] "render-guide" errored after 743 ms
10:27:13 AM: [08:27:13] "docs" errored after 1.27 min
10:27:13 AM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
10:27:13 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:27:13 AM: ​
10:27:13 AM: "build.command" failed                                        
10:27:13 AM: ────────────────────────────────────────────────────────────────
10:27:13 AM: ​
10:27:13 AM:   Error message
10:27:13 AM:   Command failed with exit code 1: yarn gulp docs (https://ntl.fyi/exit-code-1)
10:27:13 AM: ​
10:27:13 AM:   Error location
10:27:13 AM:   In build.command from netlify.toml:
10:27:13 AM:   yarn gulp docs
```

I made a second PR which just removes a spurious `return;` (#7104), and that fails in the same way. I don't think removing a return caused the Netlify issue.

**Comment by tephenavies** [comment]
Fixed in #7102 & #7100
